In [138]:
import os
import shutil
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive')
os.chdir('/content/gdrive/MyDrive/PQHIDE')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [139]:
import hashlib

import numpy as np

from utils import gaussjordan

from LinearCode import LinearCode



class QC_MDPC(LinearCode):
    """
    Quasi-Cyclic LDPC code representation (extends LinearCode)

    ...

    Methods
    -------
    from_params(n, p, w)
        Init QC-LDPC by length, circulant size and code weight

    _get_circulant_block(polynom)
        Get circulant (p, p) for given vector of size p

    """

    def __init__(self, G, H):
        super().__init__(G, H)

    @classmethod
    def from_params(cls, n, p, w):
        assert n % p == 0, "p must be delimeter of n"

        n0 = n // p
        assert w > 2*n0, "not enough code weight"

        fine = False

        while not fine:
            blocks = []
            inverse_block = None
            inverse_block_position = None

            vector = [1 for _ in range(w)] + [0 for _  in range(n - w)]
            vector = np.array(vector, dtype=int)
            np.random.shuffle(vector)

            for i in range(n0):
                circ = vector[i*p:(i+1)*p]

                if sum(circ) < 2:
                    inverse_block = None
                    break

                block = QC_MDPC._get_circulant_block(circ)
                blocks.append(block)

                A, P = gaussjordan(block, True)
                A = np.array(A, dtype=int)
                P = np.array(P, dtype=int)

                if (A == np.eye(p, dtype=int)).all():
                    inverse_block_position = i
                    inverse_block = P

            # continue only if inverse circulant found
            fine = True if inverse_block is not None else False

        # put inverse block on last position
        blocks[inverse_block_position], blocks[n0-1] = blocks[n0-1], blocks[inverse_block_position]
        H = np.concatenate(blocks, axis=1)

        for i in range(n0):
            blocks[i] = blocks[i] @ inverse_block % 2
            blocks[i] = blocks[i].T

        Ht = np.concatenate(blocks[:n0-1], axis=0)
        G = np.concatenate((np.eye(Ht.shape[0], dtype=int), Ht), axis=1)

        assert (G @ H.T % 2 == 0).all(), "G is not correspond to H"

        return cls(G, H)

    @staticmethod
    def _get_circulant_block(polynom):
        N = len(polynom)
        block = np.empty((N, N), dtype=int)

        for i in range(N):
            block[i] = np.roll(polynom, i)

        return block



# EXAMPLE USAGE:

n = 8
p = 4
w = 5
errors_num = 2
qc_mdpc = QC_MDPC.from_params(n, p, w)

word = np.random.randint(2, size=qc_mdpc.getG().shape[0])
print(word)

encoded = qc_mdpc.encode(word)
print(encoded)
print(len(encoded))

# error vector size n with t or less errors
e = [1 for _ in range(errors_num)] + [0 for _  in range(n - errors_num)]
e = np.array(e, dtype=int)
np.random.shuffle(e)
print(e)
print(len(e))

corrupted = (encoded + e) % 2
print(corrupted)
print(len(corrupted))

decoded = qc_mdpc.decode(np.copy(corrupted))
decoded = qc_mdpc.get_message(decoded)
print(decoded)
print(len(decoded))

try:
    assert (decoded == word).all()
except AssertionError:
    print("The secret message must be reforwarded")

[0 0 1 0]
[0 0 1 0 0 0 1 1]
8
[0 0 1 1 0 0 0 0]
8
[0 0 0 1 0 0 1 1]
8
[1 0 1 1]
4
The secret message must be reforwarded


In [140]:
os.chdir('/content/gdrive/MyDrive/PQHIDE/Species')

In [141]:
folder_path = '/content/gdrive/MyDrive/PQHIDE/Species/file.txt'

folder_names = []

with open(folder_path, 'r') as f:
  for line in f:
    folder_names.append(line.strip()) # strip() removes potential newline characters


# Create the empty folders
for folder_name in folder_names:
  if not os.path.exists(folder_name):
      os.makedirs(folder_name)

In [142]:
count = 0
for folder_name in folder_names:
    if(os.path.isdir(os.path.join(folder_name))):
        count = count + 1

print(count)

5011


In [143]:
ls

'Abalone jingle shell'/            'Little-fox miter'/
'Abalones nei'/                    'Little gulper shark'/
'Acadian redfish'/                 'Little pitcher conch'/
'Acoupa weakfish'/                 'Littlescale threadfin'/
'Aculeate rock shell'/             'Little skate'/
"Adanson's gibbula"/               'Little sleeper shark'/
"Adanson's moon snail"/            'Little squid'/
"Adanson's tagelus"/               'Little tunny(=Atl.black skipj)'/
'Adelie penguin'/                  'Live sharksucker'/
'Aden splitfin'/                   'Livid cone'/
'Adonis shrimp'/                   'Lizardfishes nei'/
'Adriatic horse mussel'/           'Lizard mantis'/
'Adriatic sturgeon'/               'Lobed octopus'/
'Adriatic wrack'/                  'Lobsters nei'/
'Adusta miter'/                    'Locust lobsters nei'/
'Adusta murex'/                    'Loggerhead turtle'/
'Aesop shrimp'/                    'Lollipop catshark'/
'Africa-bighead catfish hybrid'/   'Lombardy brook lam

In [144]:
value = 0
dico = {}
for filename in os.listdir('/content/gdrive/MyDrive/PQHIDE/Species'):
        if(os.path.isdir(filename)):
          dico[value]  = filename
          value = value + 1

In [145]:
 for i in dico.items():
    print(i)

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
(11, 'Spiny cockle')
(12, 'European prickly cockle')
(13, 'Poorly ribbed cockle')
(14, 'Sand cockle')
(15, 'Tuberculate cockle')
(16, 'Wahoo')
(17, 'Goldsilk seabream')
(18, 'Twobar seabream')
(19, 'Yellowfin seabream')
(20, 'Blackhead seabream')
(21, 'Surgeonfishes nei')
(22, 'Powderblue surgeonfish')
(23, 'Monrovia doctorfish')
(24, "Rathbun's giant file shell")
(25, 'Aviu shrimp')
(26, 'Australian paste shrimp')
(27, 'Northern mauxia shrimp')
(28, 'Tsivakihini paste shrimp')
(29, 'Jawla paste shrimp')
(30, 'Taiwan mauxia shrimp')
(31, 'Akiami paste shrimp')
(32, 'Southern mauxia shrimp')
(33, 'Alamang shrimp')
(34, 'Jembret shrimp')
(35, 'Siberian sturgeon')
(36, "Danube sturgeon'Green sturgeon")
(37, 'Adriatic sturgeon')
(38, 'Fringebarbel sturgeon')
(39, 'Sterlet sturgeon')
(40, 'Starry sturgeon')
(41, 'Sturgeon')
(42, 'White sturgeon')
(43, 'Sturgeons nei')
(44, 'Glowbelly')
(45, 'Glow-bellies splitfins

In [146]:
y = corrupted
print(y)
len(y)

[0 0 0 1 0 0 1 1]


8

In [147]:
lis = []
i = 0

while i < len(y):
    print(dico[i])
    count = 0
    for filename in os.listdir('/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]):
        print(filename)
        count  = count + 1
    lis.append(count)
    print("-- nombre de fichiers  = ", lis[i],"--")
    print("\n")
    i = i + 1

Starry triggerfish
Serranidae.txt
Acropomatidae.txt
Cyprinidae.txt
Nephropidae.txt
Sergestidae.txt
Scombridae.txt
Belonidae.txt
Limidae.txt
Balistidae.txt
-- nombre de fichiers  =  9 --


Flat needlefish
Serranidae.txt
Cyprinidae.txt
Acipenseridae.txt
Enoploteuthidae.txt
Limidae.txt
Octopodidae.txt
Scombridae.txt
Pectinidae.txt
Sergestidae.txt
-- nombre de fichiers  =  9 --


Verany's enope squid
Sparidae.txt
Scombridae.txt
Axiidae.txt
Serranidae.txt
Belonidae.txt
Pectinidae.txt
Cyprinidae.txt
Enoploteuthidae.txt
Balistidae.txt
Acropomatidae.txt
-- nombre de fichiers  =  10 --


Pfeffer's enope squid
Sparidae.txt
Octopodidae.txt
Serranidae.txt
Balistidae.txt
Pectinidae.txt
Holothuriidae.txt
-- nombre de fichiers  =  6 --


Freshwater bream
Nephropidae.txt
Scombridae.txt
Sparidae.txt
Enoploteuthidae.txt
Acanthuridae.txt
-- nombre de fichiers  =  5 --


Freshwater breams nei
Octopodidae.txt
Sergestidae.txt
Acropomatidae.txt
Enoploteuthidae.txt
Cyprinidae.txt
Holothuriidae.txt
Serranidae.

In [148]:
lis

[9, 9, 10, 6, 5, 8, 4, 1]

In [149]:
def hash_directory(path):
    digest = hashlib.sha256()

    for root, dirs, files in os.walk(path):
        for names in files:
            file_path = os.path.join(root, names)

            # Hash the path and add to the digest to account for empty files/directories
            digest.update(hashlib.sha1(file_path[len(path):].encode()).digest())

            # Per @pt12lol - if the goal is uniqueness over repeatability, this is an alternative method using 'hash'
            # digest.update(str(hash(file_path[len(path):])).encode())

            if os.path.isfile(file_path):
                with open(file_path, 'rb') as f_obj:
                    while True:
                        buf = f_obj.read(1024 * 1024)
                        if not buf:
                            break
                        digest.update(buf)

    return digest.hexdigest()

In [150]:
list_Hash1 = []
for i in range(len(y)):
    list_Hash1.append('')
list_Hash1

['', '', '', '', '', '', '', '']

In [151]:
for i in range(len(y)):
    path = '/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]
    list_Hash1[i] = hash_directory(path)
    print('--hash '+dico[i],'--',list_Hash1[i])

--hash Starry triggerfish -- ac20340c6073966c2f1833179ece48dec38300da43a80aa42136df00e7538378
--hash Flat needlefish -- d9fb0be9f6da40c8f9f3e33468ea04cab5980740dbcc534f26c0e6efe31d603a
--hash Verany's enope squid -- eccbc6fafc563af913bcd5746991868b3133c14b7861aa8bb238c4bd374f237d
--hash Pfeffer's enope squid -- ec66e8f3885080cb43d3f891a7e4bff9f51b6f421bf0ea6edfdbe32daca47cbd
--hash Freshwater bream -- e0a09f55b46ef7faae55fa8aa371d23a3c214dec847983ce4bcf4c69e84f6c09
--hash Freshwater breams nei -- efbf0deedc80a8aed7cdb5f0ae163b0f7daf751b81d88fc0ca3f465fdc5ebbb3
--hash Atlantic deep-sea lobster -- 4dc03f061f8277d23e3468f385ccfa844058afdf69373884956b78fcb670ef3b
--hash Prickly deep-sea lobster -- 585e3bbb9f662afbe8524420a18b37f927e826fd5996d1ca9597b3fe40269bfe


In [152]:
y

array([0, 0, 0, 1, 0, 0, 1, 1])

In [153]:
liste = ['Balistidae', 'Belonidae', 'Enoploteuthidae', 'Cyprinidae', 'Nephropidae', 'Axiidae', 'Serranidae', 'Cardiidae', 'Scombridae', 'Sparidae', 'Acanthuridae', 'Limidae', 'Sergestidae', 'Acipenseridae', 'Acropomatidae', 'Holothuriidae', 'Squalidae', 'Octopodidae', 'Pectinidae', 'Serranidae']

In [154]:
len(liste)

20

In [155]:
i = 0
while i < len(y):
    number = np.random.randint(0,20)
    file = '/'+liste[number]+'.txt'
    if(y[i] == 1):
        my_path = '/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]
        os.chdir(my_path)
        if not os.path.exists(my_path + file):
            with open(my_path + file,'w') as fp:
                pass
        else:
            descriptor = open(my_path + file,'a')
            descriptor.write("Species")
            descriptor.close()
    i = i + 1

In [156]:
lis = []
i = 0

while i < len(y):
    print(dico[i])
    count = 0
    for filename in os.listdir('/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]):
        print(filename)
        count  = count + 1
    lis.append(count)
    print("-- nombre de fichiers  = ", lis[i],"--")
    print("\n")
    i = i + 1

Starry triggerfish
Serranidae.txt
Acropomatidae.txt
Cyprinidae.txt
Nephropidae.txt
Sergestidae.txt
Scombridae.txt
Belonidae.txt
Limidae.txt
Balistidae.txt
-- nombre de fichiers  =  9 --


Flat needlefish
Serranidae.txt
Cyprinidae.txt
Acipenseridae.txt
Enoploteuthidae.txt
Limidae.txt
Octopodidae.txt
Scombridae.txt
Pectinidae.txt
Sergestidae.txt
-- nombre de fichiers  =  9 --


Verany's enope squid
Sparidae.txt
Scombridae.txt
Axiidae.txt
Serranidae.txt
Belonidae.txt
Pectinidae.txt
Cyprinidae.txt
Enoploteuthidae.txt
Balistidae.txt
Acropomatidae.txt
-- nombre de fichiers  =  10 --


Pfeffer's enope squid
Sparidae.txt
Octopodidae.txt
Serranidae.txt
Balistidae.txt
Pectinidae.txt
Holothuriidae.txt
Limidae.txt
-- nombre de fichiers  =  7 --


Freshwater bream
Nephropidae.txt
Scombridae.txt
Sparidae.txt
Enoploteuthidae.txt
Acanthuridae.txt
-- nombre de fichiers  =  5 --


Freshwater breams nei
Octopodidae.txt
Sergestidae.txt
Acropomatidae.txt
Enoploteuthidae.txt
Cyprinidae.txt
Holothuriidae.txt

In [157]:
list_Hash2 = []
for i in range(len(y)):
    list_Hash2.append('')
list_Hash2

['', '', '', '', '', '', '', '']

In [158]:
for i in range(len(y)):
    path = '/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]
    list_Hash2[i] = hash_directory(path)
    print('--hash '+dico[i],'--',list_Hash2[i])

--hash Starry triggerfish -- ac20340c6073966c2f1833179ece48dec38300da43a80aa42136df00e7538378
--hash Flat needlefish -- d9fb0be9f6da40c8f9f3e33468ea04cab5980740dbcc534f26c0e6efe31d603a
--hash Verany's enope squid -- eccbc6fafc563af913bcd5746991868b3133c14b7861aa8bb238c4bd374f237d
--hash Pfeffer's enope squid -- 626983828b66a0e60b2f0fa89ed345e8c27aff7ada3d6cb4e2c3c8ac99a18865
--hash Freshwater bream -- e0a09f55b46ef7faae55fa8aa371d23a3c214dec847983ce4bcf4c69e84f6c09
--hash Freshwater breams nei -- efbf0deedc80a8aed7cdb5f0ae163b0f7daf751b81d88fc0ca3f465fdc5ebbb3
--hash Atlantic deep-sea lobster -- cb901db7152969bfd5660aa391edfb10d94a82bf64acbb91925f175d0b60dfe5
--hash Prickly deep-sea lobster -- d2d87a9569155aba6839d16b384b70bbf1bef87ba6fe14fa4e14c04c05e4950f


In [159]:
msg_secret = []
for i in range(len(y)):
    if(list_Hash1[i] != list_Hash2[i]):
        msg_secret.append(1)
    else:
        msg_secret.append(0)

In [160]:
np.array(msg_secret)

array([0, 0, 0, 1, 0, 0, 1, 1])

In [161]:
y

array([0, 0, 0, 1, 0, 0, 1, 1])

In [162]:
len(msg_secret)

8

In [163]:
decoded = qc_mdpc.decode(np.copy(corrupted))
decoded = qc_mdpc.get_message(decoded)
print(decoded)
print(len(decoded))

[0 0 1 0]
4


In [164]:
word

array([0, 0, 1, 0])

In [165]:
try:
    assert (msg_secret == y).all()
    assert (decoded == word).all()
except AssertionError:
    print("The secret message must be reforwarded")
else:
    print("The secret message has been correctly forwarded")

The secret message has been correctly forwarded


# #Code script for time evaluation

In [169]:
from google.colab import drive
drive.mount('/content/gdrive')
os.chdir('/content/gdrive/MyDrive/PQHIDE')
import time
import os
import shutil
import numpy as np
from utils import gaussjordan
from LinearCode import LinearCode
import hashlib
from collections import defaultdict


class QC_MDPC(LinearCode):
    """
    Quasi-Cyclic LDPC code representation (extends LinearCode)

    ...

    Methods
    -------
    from_params(n, p, w)
        Init QC-LDPC by length, circulant size and code weight

    _get_circulant_block(polynom)
        Get circulant (p, p) for given vector of size p

    """

    def __init__(self, G, H):
        super().__init__(G, H)

    @classmethod
    def from_params(cls, n, p, w):
        assert n % p == 0, "p must be delimeter of n"

        n0 = n // p
        assert w > 2*n0, "not enough code weight"

        fine = False

        while not fine:
            blocks = []
            inverse_block = None
            inverse_block_position = None

            vector = [1 for _ in range(w)] + [0 for _  in range(n - w)]
            vector = np.array(vector, dtype=int)
            np.random.shuffle(vector)

            for i in range(n0):
                circ = vector[i*p:(i+1)*p]

                if sum(circ) < 2:
                    inverse_block = None
                    break

                block = QC_MDPC._get_circulant_block(circ)
                blocks.append(block)

                A, P = gaussjordan(block, True)
                A = np.array(A, dtype=int)
                P = np.array(P, dtype=int)

                if (A == np.eye(p, dtype=int)).all():
                    inverse_block_position = i
                    inverse_block = P

            # continue only if inverse circulant found
            fine = True if inverse_block is not None else False

        # put inverse block on last position
        blocks[inverse_block_position], blocks[n0-1] = blocks[n0-1], blocks[inverse_block_position]
        H = np.concatenate(blocks, axis=1)

        for i in range(n0):
            blocks[i] = blocks[i] @ inverse_block % 2
            blocks[i] = blocks[i].T

        Ht = np.concatenate(blocks[:n0-1], axis=0)
        G = np.concatenate((np.eye(Ht.shape[0], dtype=int), Ht), axis=1)

        assert (G @ H.T % 2 == 0).all(), "G is not correspond to H"

        return cls(G, H)

    @staticmethod
    def _get_circulant_block(polynom):
        N = len(polynom)
        block = np.empty((N, N), dtype=int)

        for i in range(N):
            block[i] = np.roll(polynom, i)

        return block



# EXAMPLE USAGE:

n = 8
p = 4
w = 5
errors_num = 2

qc_mdpc = QC_MDPC.from_params(n, p, w)

start = time.time()

word = np.random.randint(2, size=qc_mdpc.getG().shape[0])
print(word)

encoded = qc_mdpc.encode(word)
print(encoded)
print(len(encoded))

# error vector size n with t or less errors
e = [1 for _ in range(errors_num)] + [0 for _  in range(n - errors_num)]
e = np.array(e, dtype=int)
np.random.shuffle(e)
print(e)
print(len(e))

corrupted = (encoded + e) % 2
print(corrupted)
print(len(corrupted))


value = 0
dico = {}
for filename in os.listdir('/content/gdrive/MyDrive/PQHIDE/Species'):
        #if(os.path.isdir(filename)):
          dico[value]  = filename
          value = value + 1

y = corrupted

list_Hash1 = []
for i in range(len(y)):
    list_Hash1.append('')


for i in range(len(y)):
    path = '/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]
    list_Hash1[i] = hash_directory(path)


liste = ['Balistidae', 'Belonidae', 'Enoploteuthidae', 'Cyprinidae', 'Nephropidae', 'Axiidae', 'Serranidae', 'Cardiidae', 'Scombridae', 'Sparidae', 'Acanthuridae', 'Limidae', 'Sergestidae', 'Acipenseridae', 'Acropomatidae', 'Holothuriidae', 'Squalidae', 'Octopodidae', 'Pectinidae', 'Serranidae']

i = 0
while i < len(y):
    number = np.random.randint(0,20)
    file = '/'+liste[number]+'.txt'
    if(y[i] == 1):
        my_path = '/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]
        os.chdir(my_path)
        if not os.path.exists(my_path + file):
            with open(my_path + file,'w') as fp:
                pass
        else:
            descriptor = open(my_path + file,'a')
            descriptor.write("Species")
            descriptor.close()
    i = i + 1



list_Hash2 = []
for i in range(len(y)):
    list_Hash2.append('')


for i in range(len(y)):
    path = '/content/gdrive/MyDrive/PQHIDE/Species/' + dico[i]
    list_Hash2[i] = hash_directory(path)


msg_secret = []
for i in range(len(y)):
    if(list_Hash1[i] != list_Hash2[i]):
        msg_secret.append(1)
    else:
        msg_secret.append(0)


decoded = qc_mdpc.decode(np.copy(corrupted))
decoded = qc_mdpc.get_message(decoded)
print(decoded)
print(len(decoded))

end = time.time()
print('time = ',end - start)

try:
    assert (msg_secret == y).all()
    assert (decoded == word).all()
except AssertionError:
    print("The secret message must be reforwarded")
else:
    print("The secret message has been correctly forwarded")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
[0 1 1 1]
[0 1 1 1 1 0 0 1]
8
[0 1 0 0 1 0 0 0]
8
[0 0 1 1 0 0 0 1]
8
[0 0 1 1]
4
time =  0.4419369697570801
The secret message must be reforwarded
